# Generated by Django 4.2.27 on 2026-01-07 15:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre del remitente', max_length=100, verbose_name='Nombre')),
                ('email', models.EmailField(help_text='Correo electrónico del remitente', max_length=254, verbose_name='Email')),
                ('mensaje', models.TextField(help_text='Contenido del mensaje', verbose_name='Mensaje')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('leido', models.BooleanField(default=False, help_text='Marcar cuando el mensaje haya sido leído', verbose_name='Leído')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'verbose_name_plural': 'Mensajes de Contacto',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Facet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text="Título de la faceta (ej. 'El Alquimista', 'El Líder')", max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción general de la faceta', verbose_name='Descripción')),
                ('imagen_hero', models.ImageField(blank=True, help_text='Imagen principal de la faceta (recomendado: 1920x1080px)', null=True, upload_to='facetas/hero/', verbose_name='Imagen Hero')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('slug', models.SlugField(blank=True, help_text='URL amigable (se genera automáticamente desde el título)', max_length=200, unique=True, verbose_name='Slug')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar esta faceta del sitio público', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Faceta',
                'verbose_name_plural': 'Facetas',
                'ordering': ['orden', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Milestone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del hito', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción detallada del hito', verbose_name='Descripción')),
                ('año', models.IntegerField(blank=True, help_text='Año del hito', null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2100)], verbose_name='Año')),
                ('imagen', models.ImageField(blank=True, help_text='Imagen del hito (recomendado: 1200x800px)', null=True, upload_to='hitos/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización dentro de la faceta (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar este hito del sitio público', verbose_name='Activo')),
                ('faceta', models.ForeignKey(help_text='Faceta a la que pertenece este hito', on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='core.facet', verbose_name='Faceta')),
            ],
            options={
                'verbose_name': 'Hito',
                'verbose_name_plural': 'Hitos',
                'ordering': ['faceta', 'orden', 'año', 'titulo'],
            },
        ),
        migrations.AddIndex(
            model_name='facet',
            index=models.Index(fields=['orden', 'activo'], name='core_facet_orden_2db538_idx'),
        ),
        migrations.AddIndex(
            model_name='facet',
            index=models.Index(fields=['slug'], name='core_facet_slug_3a995d_idx'),
        ),
        migrations.AddIndex(
            model_name='contactmessage',
            index=models.Index(fields=['-fecha_creacion', 'leido'], name='core_contac_fecha_c_43eeb8_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['faceta', 'orden', 'activo'], name='core_milest_faceta__09f06a_idx'),
        ),
        migrations.AddIndex(
            model_name='milestone',
            index=models.Index(fields=['año'], name='core_milest_año_abdeab_idx'),
        ),
    ]
