# Generated by Django 4.2.27 on 2026-01-07 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='imagen_hero',
            field=models.ImageField(blank=True, help_text='Imagen de fondo para la sección hero (recomendado: 1920x1080px)', null=True, upload_to='site/hero/', verbose_name='Imagen Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='subtitulo_hero',
            field=models.CharField(blank=True, default='Scroll to explore', help_text='Texto pequeño debajo del texto principal', max_length=200, verbose_name='Subtítulo Hero'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='texto_hero',
            field=models.CharField(blank=True, default='ALQUIMISTA', help_text='Texto grande que aparece en el hero', max_length=200, verbose_name='Texto Hero Principal'),
        ),
    ]
