# Generated by Django 4.2.27 on 2026-01-07 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sitesettings_imagen_hero_sitesettings_subtitulo_hero_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(help_text='Imagen adicional del hito (recomendado: 1920x1080px)', upload_to='hitos/imagenes/', verbose_name='Imagen')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar esta imagen del sitio público', verbose_name='Activo')),
                ('hito', models.ForeignKey(help_text='Hito al que pertenece esta imagen', on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='core.milestone', verbose_name='Hito')),
            ],
            options={
                'verbose_name': 'Imagen de Hito',
                'verbose_name_plural': 'Imágenes de Hitos',
                'ordering': ['hito', 'orden', '-fecha_creacion'],
                'indexes': [models.Index(fields=['hito', 'orden', 'activo'], name='core_milest_hito_id_ba5fe5_idx')],
            },
        ),
    ]
