# Generated by Django 4.2.27 on 2026-01-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_milestoneimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactmessage',
            name='fecha_respuesta',
            field=models.DateTimeField(blank=True, help_text='Fecha en que se envió la respuesta', null=True, verbose_name='Fecha de Respuesta'),
        ),
        migrations.AddField(
            model_name='contactmessage',
            name='respuesta',
            field=models.TextField(blank=True, help_text='Respuesta al mensaje del contacto', null=True, verbose_name='Respuesta'),
        ),
    ]
