# Generated by Django 4.2.27 on 2026-01-08 15:58

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0005_contactmessage_fecha_respuesta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFacetPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prioridad', models.IntegerField(default=0, help_text='Orden de prioridad (menor número = mayor prioridad)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Prioridad')),
                ('fecha_seleccion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de selección')),
                ('faceta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_preferences', to='core.facet', verbose_name='Faceta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='facet_preferences', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Preferencia de Faceta',
                'verbose_name_plural': 'Preferencias de Facetas',
                'ordering': ['usuario', 'prioridad', 'faceta__orden'],
                'indexes': [models.Index(fields=['usuario', 'prioridad'], name='core_userfa_usuario_30ceef_idx')],
                'unique_together': {('usuario', 'faceta')},
            },
        ),
    ]
