# Generated by Django 4.2.27 on 2026-01-08 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_userfacetpreference'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='video',
            field=models.FileField(blank=True, help_text='Video del hito (opcional, formatos: mp4, webm, mov)', null=True, upload_to='hitos/videos/', verbose_name='Video'),
        ),
        migrations.AddField(
            model_name='milestone',
            name='video_url',
            field=models.URLField(blank=True, help_text='URL de video externo (YouTube, Vimeo, etc.) - Opcional', null=True, verbose_name='URL de Video'),
        ),
    ]
