# Generated by Django 4.2.27 on 2026-01-08 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_add_video_to_milestone'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='video_activo',
            field=models.BooleanField(default=True, help_text='Marcar para mostrar el video en el sitio público. Si está desmarcado, se mostrará la imagen en su lugar.', verbose_name='Video Activo'),
        ),
    ]
