# Generated by Django 4.2.27 on 2026-01-08 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_add_video_activo_field'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sitesettings',
            name='subtitulo_hero',
        ),
        migrations.RemoveField(
            model_name='sitesettings',
            name='texto_hero',
        ),
    ]
