# Generated by Django 4.2.27 on 2026-01-08 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_texto_hero_and_subtitulo_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestone',
            name='tamaño_imagen',
            field=models.CharField(choices=[('grande', 'Grande'), ('mediana', 'Mediana'), ('pequeña', 'Pequeña')], default='mediana', help_text='Tamaño de visualización de la imagen principal', max_length=10, verbose_name='Tamaño de Imagen'),
        ),
    ]
