# Generated by Django 4.2.27 on 2026-01-09 03:22

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0011_limit_descripcion_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono para WhatsApp (formato: +56912345678)', max_length=20, verbose_name='Teléfono WhatsApp'),
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título de la temática', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción de la temática', verbose_name='Descripción')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar esta temática del sitio público', verbose_name='Activo')),
            ],
            options={
                'verbose_name': 'Temática',
                'verbose_name_plural': 'Temáticas',
                'ordering': ['orden', 'titulo'],
                'indexes': [models.Index(fields=['orden', 'activo'], name='core_temati_orden_5a6750_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rol', models.CharField(choices=[('visitante', 'Visitante'), ('estudiante', 'Estudiante')], default='visitante', help_text='Rol del usuario en el sistema', max_length=20, verbose_name='Rol')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Perfil de Usuario',
                'verbose_name_plural': 'Perfiles de Usuario',
                'indexes': [models.Index(fields=['rol'], name='core_userpr_rol_d716a8_idx')],
            },
        ),
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='Título del material', max_length=200, verbose_name='Título')),
                ('descripcion', models.TextField(blank=True, help_text='Descripción del material', verbose_name='Descripción')),
                ('archivo_pdf', models.FileField(blank=True, help_text='Archivo PDF del material (opcional)', null=True, upload_to='materiales/pdfs/', verbose_name='Archivo PDF')),
                ('video_url', models.URLField(blank=True, help_text='URL de video externo (YouTube, Vimeo, etc.) - Opcional', null=True, verbose_name='URL de Video')),
                ('video_archivo', models.FileField(blank=True, help_text='Archivo de video local (opcional, formatos: mp4, webm, mov)', null=True, upload_to='materiales/videos/', verbose_name='Archivo de Video')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización dentro de la temática (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar este material del sitio público', verbose_name='Activo')),
                ('tematica', models.ForeignKey(help_text='Temática a la que pertenece este material', on_delete=django.db.models.deletion.CASCADE, related_name='materiales', to='core.tematica', verbose_name='Temática')),
            ],
            options={
                'verbose_name': 'Material',
                'verbose_name_plural': 'Materiales',
                'ordering': ['tematica', 'orden', 'titulo'],
                'indexes': [models.Index(fields=['tematica', 'orden', 'activo'], name='core_materi_tematic_1c9cec_idx')],
            },
        ),
    ]
