# Generated by Django 4.2.27 on 2026-01-09 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_sitesettings_whatsapp_telefono_tematica_userprofile_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='video_hero',
            field=models.FileField(blank=True, help_text='Video para la sección hero (opcional, formatos: mp4, webm, mov). Se mostrará después de la imagen al hacer scroll.', null=True, upload_to='site/hero/videos/', verbose_name='Video Hero'),
        ),
    ]
