# Generated by Django 4.2.27 on 2026-01-09 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_sitesettings_video_hero'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='biografia',
            field=models.TextField(blank=True, help_text='Breve descripción sobre ti (máximo 500 caracteres)', max_length=500, verbose_name='Biografía'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='ciudad',
            field=models.CharField(blank=True, help_text='Ciudad de residencia', max_length=100, verbose_name='Ciudad'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, help_text='Fecha de nacimiento (opcional)', null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='foto_perfil',
            field=models.ImageField(blank=True, help_text='Foto de perfil del usuario (opcional)', null=True, upload_to='perfiles/', verbose_name='Foto de Perfil'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='instagram_url',
            field=models.URLField(blank=True, help_text='URL de tu perfil de Instagram (opcional)', verbose_name='Instagram URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='linkedin_url',
            field=models.URLField(blank=True, help_text='URL de tu perfil de LinkedIn (opcional)', verbose_name='LinkedIn URL'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre_completo',
            field=models.CharField(blank=True, help_text='Nombre completo del usuario', max_length=200, verbose_name='Nombre Completo'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='pais',
            field=models.CharField(blank=True, help_text='País de residencia', max_length=100, verbose_name='País'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='sitio_web',
            field=models.URLField(blank=True, help_text='URL de tu sitio web personal o portfolio (opcional)', verbose_name='Sitio Web'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='telefono',
            field=models.CharField(blank=True, help_text='Número de teléfono de contacto', max_length=20, verbose_name='Teléfono'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='twitter_url',
            field=models.URLField(blank=True, help_text='URL de tu perfil de Twitter/X (opcional)', verbose_name='Twitter/X URL'),
        ),
        migrations.AddIndex(
            model_name='userprofile',
            index=models.Index(fields=['pais', 'ciudad'], name='core_userpr_pais_fdcdce_idx'),
        ),
    ]
