# Generated by Django 4.2.27 on 2026-01-09 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_userprofile_biografia_userprofile_ciudad_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='userprofile',
            name='core_userpr_pais_fdcdce_idx',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='biografia',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='foto_perfil',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='instagram_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='linkedin_url',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='nombre_completo',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='pais',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='sitio_web',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='telefono',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='twitter_url',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='id_usuario',
            field=models.CharField(blank=True, help_text='Identificación del usuario (RUT, DNI, etc.)', max_length=50, verbose_name='ID'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nombre',
            field=models.CharField(blank=True, help_text='Nombre completo del usuario', max_length=200, verbose_name='Nombre'),
        ),
    ]
