# Generated by Django 4.2.27 on 2026-01-09 15:02

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_userprofile_core_userpr_pais_fdcdce_idx_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='archivo_pdf',
        ),
        migrations.RemoveField(
            model_name='material',
            name='video_archivo',
        ),
        migrations.RemoveField(
            model_name='material',
            name='video_url',
        ),
        migrations.CreateModel(
            name='MaterialVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video_url', models.URLField(blank=True, help_text='URL de video externo (YouTube, Vimeo, etc.) - Opcional si se sube un archivo', null=True, verbose_name='URL de Video')),
                ('video_archivo', models.FileField(blank=True, help_text='Archivo de video local (opcional si se proporciona una URL, formatos: mp4, webm, mov)', null=True, upload_to='materiales/videos/', verbose_name='Archivo de Video')),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo del video (opcional)', max_length=200, verbose_name='Nombre')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar este video', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('material', models.ForeignKey(help_text='Material al que pertenece este video', on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='core.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Video de Material',
                'verbose_name_plural': 'Videos de Materiales',
                'ordering': ['material', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['material', 'orden', 'activo'], name='core_materi_materia_ff82e3_idx')],
            },
        ),
        migrations.CreateModel(
            name='MaterialPDF',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo PDF (formato: PDF)', upload_to='materiales/pdfs/', verbose_name='Archivo PDF')),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo del PDF (opcional, si no se proporciona se usará el nombre del archivo)', max_length=200, verbose_name='Nombre')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar este PDF', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('material', models.ForeignKey(help_text='Material al que pertenece este PDF', on_delete=django.db.models.deletion.CASCADE, related_name='pdfs', to='core.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'PDF de Material',
                'verbose_name_plural': 'PDFs de Materiales',
                'ordering': ['material', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['material', 'orden', 'activo'], name='core_materi_materia_1efb5a_idx')],
            },
        ),
    ]
