# Generated by Django 4.2.27 on 2026-01-09 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_remove_material_archivo_pdf_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='imagen_loading',
            field=models.ImageField(blank=True, help_text='Imagen que se muestra en el centro de la pantalla de carga (recomendado: 200x200px o más)', null=True, upload_to='site/loading/', verbose_name='Imagen de Loading'),
        ),
    ]
