# Generated by Django 4.2.27 on 2026-01-10 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_sitesettings_imagen_loading'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesettings',
            name='imagen_loading',
            field=models.ImageField(blank=True, help_text='Imagen que se muestra en el centro de la pantalla de carga (recomendado: 200x200px o más). Si no se selecciona, se usará el logo del sitio.', null=True, upload_to='site/loading/', verbose_name='Imagen de Loading'),
        ),
    ]
