# Generated by Django 4.2.27 on 2026-01-10 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_alter_sitesettings_imagen_loading'),
    ]

    operations = [
        migrations.AddField(
            model_name='facet',
            name='color_fondo',
            field=models.CharField(choices=[('negro', 'Negro'), ('blanco', 'Blanco')], default='negro', help_text='Color de fondo para esta faceta (Negro o Blanco)', max_length=10, verbose_name='Color de Fondo'),
        ),
    ]
