# Generated by Django 4.2.27 on 2026-01-11 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_facet_color_fondo'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='imagen',
            field=models.ImageField(blank=True, help_text='Imagen representativa del material (opcional)', null=True, upload_to='materiales/imagenes/', verbose_name='Imagen'),
        ),
    ]
