# Generated by Django 4.2.27 on 2026-01-11 17:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_add_imagen_to_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='material',
            name='imagen',
        ),
    ]
