# Generated by Django 4.2.27 on 2026-01-11 17:47

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_remove_imagen_add_presentaciones'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaterialPresentacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archivo', models.FileField(help_text='Archivo de presentación (formatos: ppt, pptx, pdf, odp)', upload_to='materiales/presentaciones/', verbose_name='Archivo de Presentación')),
                ('nombre', models.CharField(blank=True, help_text='Nombre descriptivo de la presentación (opcional)', max_length=200, verbose_name='Nombre')),
                ('orden', models.IntegerField(default=0, help_text='Orden de visualización (menor número = aparece primero)', validators=[django.core.validators.MinValueValidator(0)], verbose_name='Orden')),
                ('activo', models.BooleanField(default=True, help_text='Desmarcar para ocultar esta presentación', verbose_name='Activo')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('material', models.ForeignKey(help_text='Material al que pertenece esta presentación', on_delete=django.db.models.deletion.CASCADE, related_name='presentaciones', to='core.material', verbose_name='Material')),
            ],
            options={
                'verbose_name': 'Presentación de Material',
                'verbose_name_plural': 'Presentaciones de Materiales',
                'ordering': ['material', 'orden', 'nombre'],
                'indexes': [models.Index(fields=['material', 'orden', 'activo'], name='core_materi_materia_b1de8e_idx')],
            },
        ),
    ]
