"""
Django settings for alquimista_project project.

Generated by 'django-admin startproject' using Django 5.2.8.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
import os

# Load environment variables from .env file (if python-dotenv is installed)
try:
    from dotenv import load_dotenv
    load_dotenv()
except ImportError:
    pass  # python-dotenv no está instalado, usar variables de entorno del sistema

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-r+7dds)gsc7&xh3)5ku3^v-2j1+=sb#zndtg0@ys!*f(fetz+@')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True') == 'True'

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'e81b08a7b841.ngrok-free.app']

# En desarrollo, permitir cualquier host si DEBUG está activo (útil para ngrok que cambia de dominio)
if DEBUG:
    ALLOWED_HOSTS = ['*']

# CSRF Trusted Origins (para ngrok y otros proxies)
# IMPORTANTE: Si cambias el dominio de ngrok, actualiza esta lista con el nuevo dominio
# Formato: 'https://tu-dominio.ngrok-free.app'
CSRF_TRUSTED_ORIGINS = [
    'https://e81b08a7b841.ngrok-free.app',
    'http://localhost:8000',
    'http://127.0.0.1:8000',
]

# En desarrollo, agregar configuración flexible para ngrok
if DEBUG:
    # Permitir CSRF desde cualquier origen en desarrollo (SOLO PARA DESARROLLO)
    # En producción, esto DEBE estar deshabilitado por seguridad
    CSRF_COOKIE_SECURE = False  # Permitir cookies CSRF en HTTP
    CSRF_COOKIE_HTTPONLY = False  # Permitir acceso desde JavaScript si es necesario
    CSRF_USE_SESSIONS = False  # Usar cookies en lugar de sesiones para CSRF
    CSRF_COOKIE_SAMESITE = 'Lax'  # Permitir cookies en contextos cross-site en desarrollo
    
    # Si necesitas agregar más dominios de ngrok, añádelos aquí
    # Nota: Django no soporta wildcards en CSRF_TRUSTED_ORIGINS
    # Si cambias el dominio de ngrok, actualiza esta lista manualmente
    # O usa la variable de entorno CSRF_TRUSTED_ORIGINS si está disponible
    import os
    additional_origins = os.getenv('CSRF_TRUSTED_ORIGINS', '')
    if additional_origins:
        CSRF_TRUSTED_ORIGINS.extend([origin.strip() for origin in additional_origins.split(',')])
    
    # Agregar cualquier dominio ngrok que se detecte automáticamente
    # Esto es útil cuando ngrok cambia de dominio frecuentemente
    # IMPORTANTE: En producción, esto debe estar deshabilitado
    def get_ngrok_domains():
        """Intenta detectar dominios ngrok comunes"""
        ngrok_domains = []
        # Puedes agregar aquí dominios ngrok adicionales manualmente
        # Ejemplo: ngrok_domains.append('https://nuevo-dominio.ngrok-free.app')
        # 
        # INSTRUCCIONES PARA AGREGAR NUEVO DOMINIO NGROK:
        # 1. Copia el nuevo dominio de ngrok (ejemplo: https://abc123.ngrok-free.app)
        # 2. Agrega la línea: ngrok_domains.append('https://abc123.ngrok-free.app')
        # 3. También agrégalo a CSRF_TRUSTED_ORIGINS arriba
        # 4. Reinicia el servidor Django
        return ngrok_domains
    
    ngrok_domains = get_ngrok_domains()
    for domain in ngrok_domains:
        if domain not in CSRF_TRUSTED_ORIGINS:
            CSRF_TRUSTED_ORIGINS.append(domain)


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.sitemaps',  # Para sitemap.xml
    'core',  # Nuestra app principal
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'alquimista_project.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django.template.context_processors.media',
                'core.context_processors.staff_context',
            ],
        },
    },
]

WSGI_APPLICATION = 'alquimista_project.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': os.getenv('DB_NAME', 'alquimista_db'),
        'USER': os.getenv('DB_USER', 'root'),
        'PASSWORD': os.getenv('DB_PASSWORD', ''),
        'HOST': os.getenv('DB_HOST', 'localhost'),
        'PORT': os.getenv('DB_PORT', '3306'),
        'OPTIONS': {
            'init_command': "SET sql_mode='STRICT_TRANS_TABLES'",
            'charset': 'utf8mb4',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
        'OPTIONS': {
            'user_attributes': ('username', 'email'),
            'max_similarity': 0.7,
        },
        'MESSAGE': 'La contraseña es demasiado similar a tu nombre de usuario o email.',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
        'OPTIONS': {
            'min_length': 8,
        },
        'MESSAGE': 'La contraseña debe tener al menos 8 caracteres.',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
        'MESSAGE': 'Esta contraseña es muy común. Por favor, elige una contraseña más segura.',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
        'MESSAGE': 'La contraseña no puede ser completamente numérica.',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'es-es'

TIME_ZONE = 'America/Santiago'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Media files (User uploaded content)
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Cache configuration (para rate limiting)
CACHES = {
    'default': {
        'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
        'LOCATION': 'unique-snowflake',
    }
}

# Email Configuration
EMAIL_BACKEND = os.getenv('EMAIL_BACKEND', 'django.core.mail.backends.smtp.EmailBackend')
EMAIL_HOST = os.getenv('EMAIL_HOST', 'smtp.gmail.com')
EMAIL_PORT = int(os.getenv('EMAIL_PORT', '587'))
EMAIL_USE_TLS = os.getenv('EMAIL_USE_TLS', 'True') == 'True'
EMAIL_USE_SSL = os.getenv('EMAIL_USE_SSL', 'False') == 'True'  # Para puerto 465
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER', '')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD', '')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL', 'noreply@alquimista.com')
SERVER_EMAIL = DEFAULT_FROM_EMAIL

# Logging para diagnosticar problemas de email
import logging
logger = logging.getLogger(__name__)
if EMAIL_BACKEND == 'django.core.mail.backends.smtp.EmailBackend':
    logger.info(f"Email configurado para SMTP: {EMAIL_HOST}:{EMAIL_PORT}, Usuario: {EMAIL_HOST_USER}")
else:
    logger.warning(f"Email usando backend: {EMAIL_BACKEND}")

# Note: Error handlers are defined in urls.py, not in settings.py
